# tmux prefix key to Ctrl-a
unbind C-b
set -g prefix C-a
bind a send-prefix

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g status-position top

bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -h -c "#{pane_current_path}"
bind % split-window -v -c "#{pane_current_path}"

set-option -s escape-time 0

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'fabioluciano/tmux-powerkit'

set -g @powerkit_plugins ''
set -g @powerkit_transparent 'true'

run '/opt/homebrew/opt/tpm/share/tpm/tpm'
